// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl1LZeqleiEsLhwtnzVZRUAoAg_0J8tH8',
    appId: '1:572496152073:web:475debad10a8960969dad8',
    messagingSenderId: '572496152073',
    projectId: 'gravitas-auto',
    authDomain: 'gravitas-auto.firebaseapp.com',
    storageBucket: 'gravitas-auto.firebasestorage.app',
    measurementId: 'G-D3SX3Q7W14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbNF89Bj15n7AUDI7C_R7SFS2ff54WudM',
    appId: '1:572496152073:android:e5434e69ffb98b1269dad8',
    messagingSenderId: '572496152073',
    projectId: 'gravitas-auto',
    storageBucket: 'gravitas-auto.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoLZaodDDLk3MG8QLLjyhuQDg61beAiZI',
    appId: '1:572496152073:ios:d9e5232a3d5a888369dad8',
    messagingSenderId: '572496152073',
    projectId: 'gravitas-auto',
    storageBucket: 'gravitas-auto.firebasestorage.app',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoLZaodDDLk3MG8QLLjyhuQDg61beAiZI',
    appId: '1:572496152073:ios:d9e5232a3d5a888369dad8',
    messagingSenderId: '572496152073',
    projectId: 'gravitas-auto',
    storageBucket: 'gravitas-auto.firebasestorage.app',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl1LZeqleiEsLhwtnzVZRUAoAg_0J8tH8',
    appId: '1:572496152073:web:5c5cca1e7c801eda69dad8',
    messagingSenderId: '572496152073',
    projectId: 'gravitas-auto',
    authDomain: 'gravitas-auto.firebaseapp.com',
    storageBucket: 'gravitas-auto.firebasestorage.app',
    measurementId: 'G-K0KT48D3X7',
  );
}