import 'package:new_app/src/pages/home/models/car.dart'; // adjust to your actual path

final List<Car> allCars = [
  const Car(
    id: '1',
    name: 'BMW M4',
    year: '2025',
    km: '12 500 км',
    price: '65 000 \$',
    transmission: 'Автомат',
    fuelType: 'Бензин',
    engineCapacity: '3.0 л',
    bodyType: 'Купе',
    color: 'Чёрный',
    location: 'Бишкек',
  ),
  const Car(
    id: '2',
    name: 'Audi RS7',
    year: '2024',
    km: '8 300 км',
    price: '79 000 \$',
    transmission: 'Автомат',
    fuelType: 'Бензин',
    engineCapacity: '4.0 л',
    bodyType: 'Седан',
    color: 'Серый',
    location: 'Алматы',
  ),
  const Car(
    id: '3',
    name: 'Toyota Camry',
    year: '2023',
    km: '34 000 км',
    price: '28 000 \$',
    transmission: 'Автомат',
    fuelType: 'Бензин',
    engineCapacity: '2.5 л',
    bodyType: 'Седан',
    color: 'Белый',
    location: 'Бишкек',
  ),
  const Car(
    id: '4',
    name: 'Tesla Model 3',
    year: '2024',
    km: '5 200 км',
    price: '42 000 \$',
    transmission: 'Автомат',
    fuelType: 'Электро',
    engineCapacity: '—',
    bodyType: 'Седан',
    color: 'Синий',
    location: 'Алматы',
  ),
  const Car(
    id: '5',
    name: 'Hyundai Tucson',
    year: '2022',
    km: '41 000 км',
    price: '24 500 \$',
    transmission: 'Автомат',
    fuelType: 'Бензин',
    engineCapacity: '2.0 л',
    bodyType: 'Кроссовер',
    color: 'Серебристый',
    location: 'Ош',
  ),
];